### ISSUE TITLE
interop-mavproxy-module and mavprooxy_interop_obc not working

### ISSUE THREAD

**Issue by AlexisPotvin** [Dronolab/interop-mavproxy-module#2]
Hello, both modules mavproxy_interop and mavproxy_interop_obc are not working properly. 
Please fix it i have been waiting more then a month for this module.

Thx joey!

**Comment by richerlariviere** [comment]
Could you please provide steps to reproduce this issue?

Thanks

**Comment by AlexisPotvin** [comment]
Clone repro, add those modules to mavproxy and they dosent work
